# docker-compose.yml
version: '3.8'
services:
  spring-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
    volumes:
      - ./logs:/app/logs
    networks:
      - springboot-network
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - "9090:8082"
    networks:
      - springboot-network

networks:
  springboot-network:
    driver: bridge